[workspace]
members = ["types"]
resolver = "1"

[workspace.package]
edition = "2021"
rust-version = "1.72"
version = "0.1.0-alpha.4"

[workspace.dependencies]
vercre-wallet = { path = "../../../vercre-wallet" }
