[package]
name = "wallet"
description = "Example wallet client for vercre-holder crate"
license = "MIT OR Apache-2.0"
readme = "README.md"

authors.workspace = true
categories.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
# crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
base64ct.workspace = true
chrono.workspace = true
dif-exch.workspace = true
ecdsa.workspace = true
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
futures.workspace = true
http = "1.1.0"
log = "0.4.22"
reqwest = { version = "0.12.5", features = ["json"] }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2.0.0-beta.24", features = ["test"] }
tauri-plugin-deep-link = "2.0.0-beta.9"
tauri-plugin-log = "2.0.0-beta.8"
tauri-plugin-shell = "2.0.0-beta.9"
tauri-plugin-store = "2.0.0-beta.10"
test-utils.workspace = true
typeshare = "1.0.3"
urlencoding = "2.1.3"
vercre-holder.workspace = true
vercre-issuer.workspace = true
vercre-verifier.workspace = true

[dev-dependencies]

[build-dependencies]
tauri-build = { version = "2.0.0-beta.19", features = [] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
