[package]
name = "wallet"
description = "Example wallet client for vercre-holder crate"
license = "MIT OR Apache-2.0"
readme = "README.md"

authors.workspace = true
categories.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
# crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
argon2 = { version = "2.1.0", package = "rust-argon2" }
base64ct.workspace = true
chrono.workspace = true
ed25519-dalek = "2.1.1"
futures.workspace = true
http = "1.1.0"
log = "0.4.21"
reqwest = { version = "0.12.4", features = ["json"] }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2.0.0-beta.22", features = ["test"] }
tauri-plugin-deep-link = "2.0.0-beta.7"
tauri-plugin-log = "2.0.0-beta.6"
tauri-plugin-shell = "2.0.0-beta.7"
tauri-plugin-store = "2.0.0-beta.8"
typeshare = "1.0.3"
urlencoding = "2.1.3"
vercre-holder.workspace = true
vercre-vc.workspace = true

[dev-dependencies]
lazy_static.workspace = true
tokio.workspace = true

[build-dependencies]
tauri-build = { version = "2.0.0-beta.17", features = [] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
