[package]
name = "wallet"
description = "Example wallet client for vercre-holder crate"
license = "MIT OR Apache-2.0"
publish = false

authors.workspace = true
categories.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
# crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
base64ct.workspace = true
chrono.workspace = true
futures.workspace = true
http = "1.1.0"
log = "0.4.22"
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2.0.0-rc.2", features = ["test"] }
tauri-plugin-deep-link = "2.0.0-rc.0"
tauri-plugin-log = "2.0.0-rc.0"
tauri-plugin-shell = "2.0.0-rc.0"
tauri-plugin-store = "2.0.0-rc.0"
tauri-plugin-http = "2.0.0-rc.0"
typeshare = "1.0.3"
urlencoding = "2.1.3"
vercre-holder.workspace = true
vercre-test-utils.workspace = true

[dev-dependencies]

[build-dependencies]
tauri-build = { version = "2.0.0-rc.2", features = [] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
