[package]
name = "providers"
description = "Test utilities"
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
base64ct.workspace = true
chrono.workspace = true
ecdsa.workspace = true
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
k256.workspace = true
serde_json.workspace = true
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
tracing.workspace = true
uuid.workspace = true
vercre-core.workspace = true
vercre-proof.workspace = true
vercre-vc.workspace = true
