[package]
name = "credibil-vc"
description = "OpenID for Verifiable Credential Issuance and Verifiable Presentation"
readme = "README.md"
authors.workspace = true
categories.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[features]
default = ["issuer", "verifier"]
issuer = []
verifier = []
wasm = ["fastrand/js"]

[dependencies]
anyhow.workspace = true
base64ct.workspace = true
bitvec = "1.0.1"
bytes = "1.10.1"
chrono = { version = "0.4.41", features = ["serde"] }
ciborium = "0.2.2"
cid = { version = "0.11.1", features = ["alloc"] }
coset = "0.3.8"
credibil-identity.workspace = true
credibil-jose.workspace = true
credibil-se.workspace = true
fastrand = "2.3.0"
flate2 = "1.1.1"
futures.workspace = true
http = "1.3.1"
http-body = "1.0.1"
http-body-util = "0.1"
image = { version = "0.25.6", default-features = false, features = ["png"] }
multihash-codetable = { version = "0.1.4", features = ["sha2"] }
percent-encoding = "2.3.1"
qrcode = { version = "0.14.1", default-features = false, features = ["image"] }
rand = "0.9.1"
serde.workspace = true
serde_json.workspace = true
serde_repr = "0.1"
serde_urlencoded = "0.7.1"
sha2 = "0.10.9"
thiserror = "2.0.12"
tracing = "0.1.41"
uuid = { version = "1.16.0", features = ["fast-rng", "v4"] }

[dev-dependencies]
axum = { version = "0.8.4", features = ["macros"] }
axum-extra = { version = "0.10.1", features = ["typed-header"] }
hex = "0.4.3"
oauth2 = { version = "5.0.0" }
provider = { path = "crates/provider" }
rand_core.workspace = true
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.2", features = ["cors", "set-header", "trace"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
test-kms.workspace = true

[[example]]
name = "issuer"
path = "examples/issuer.rs"
# required-features = ["client", "server"]

[[example]]
name = "verifier"
path = "examples/verifier.rs"

# -----------------------------------------------
# Workspace
# -----------------------------------------------
[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["Credibil"]
categories = ["authentication", "cryptography", "data-structures"]
edition = "2024"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://credibil.io"
keywords = ["credentials", "decentralized", "identity", "openid", "verifiable"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/credibil/vc"
rust-version = "1.86"
version = "0.1.0"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
# clippy::all = correctness, suspicious, style, complexity, perf
# not using (yet) -Dclippy::restriction
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
anyhow = "1.0.98"
base64ct = { version = "1.7.3", features = ["std"] }
credibil-identity = { git = "https://github.com/credibil/identity.git" }
credibil-jose = { git = "https://github.com/credibil/jose.git" }
credibil-se = { git = "https://github.com/credibil/jose.git" }
credibil-vc = { path = "." }
futures = "0.3.31"
rand_core = "0.6.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["alloc"] }
test-kms = { git = "https://github.com/credibil/jose.git" }

[patch.crates-io]
# credibil-identity = { path = "../identity" }
# credibil-jose = { path = "../jose" }

[profile.release]
# optimize for small code size
lto = "thin"
opt-level = "s"
strip = "symbols"
