[workspace]
members = [
    "crates/*",
    "examples/issuer",
    "examples/verifier",
    "examples/wallet/src-tauri",
    "vercre-holder",
    "vercre-issuer",
    "vercre-verifier",
]
exclude = ["vercre-holder/examples/*"]
resolver = "2"

[workspace.package]
authors = ["Vercre"]
categories = ["authentication", "cryptography", "data-structures"]
edition = "2021"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://vercre.io"
keywords = ["credentials", "decentralized", "identity", "openid", "verifiable"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/vercre/vc"
rust-version = "1.80"
version = "0.1.0-alpha.6"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
# clippy::all = correctness, suspicious, style, complexity, perf
# not using (yet) -Dclippy::restriction
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
anyhow = "1.0.91"
assert_let_bind = "0.1.1"
axum = { version = "0.7.7", features = ["macros"] }
axum-extra = { version = "0.9.4", features = ["typed-header"] }
base64ct = { version = "1.6.0", features = ["std"] }
chrono = { version = "0.4.38", features = ["serde"] }
derive_builder = "0.20.2"
ecdsa = "0.16.9"
insta = { version = "1.40.0", features = ["redactions", "yaml"] }
serde = { version = "1.0.213", features = ["derive"] }
serde_json = { version = "1.0.132", features = ["alloc"] }
test-utils = { path = "crates/test-utils" }
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.1", features = ["cors", "set-header", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
uuid = { version = "1.11.0", features = ["fast-rng", "v4"] }
vercre-core = { path = "crates/core", version = "0.1.0-alpha.6" }
vercre-did = { git = "https://github.com/vercre/did.git" }
vercre-dif-exch = { path = "crates/dif-exch", version = "0.1.0-alpha.6" }
vercre-holder = { path = "vercre-holder", version = "0.1.0-alpha.6" }
vercre-infosec = { git = "https://github.com/vercre/infosec.git" }
vercre-issuer = { path = "vercre-issuer", version = "0.1.0-alpha.6" }
vercre-macros = { path = "crates/macros", version = "0.1.0-alpha.6" }
vercre-openid = { path = "crates/openid", version = "0.1.0-alpha.6" }
vercre-status = { path = "crates/status", version = "0.1.0-alpha.6" }
vercre-verifier = { path = "vercre-verifier", version = "0.1.0-alpha.6" }
vercre-w3c-vc = { path = "crates/w3c-vc", version = "0.1.0-alpha.6" }

[patch."https://github.com/vercre/infosec.git"]
vercre-infosec = { path = "../infosec" }

[workspace.metadata.bin]
cargo-xcode = { version = "=1.7.0" }

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
