[workspace]
members = [
    "crates/*",
    "examples/issuance",
    "examples/presentation",
    "examples/wallet/src-tauri",
    "vercre-holder",
    "vercre-issuer",
    "vercre-verifier",
]
exclude = ["vercre-holder/examples/*"]
resolver = "2"

[workspace.package]
authors = ["Vercre"]
categories = ["decentralized identity", "openid for verifiable data", "privacy", "security", "verifiable credentials"]
edition = "2021"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://vercre.io"
keywords = ["credentials", "decentralized", "identity", "openid", "verifiable"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/vercre/vercre"
rust-version = "1.80"
version = "0.1.0-alpha.4"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
# clippy::all = correctness, suspicious, style, complexity, perf
# not using (yet) -Dclippy::restriction
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
anyhow = "1.0.86"
assert_let_bind = "0.1.1"
axum = { version = "0.7.5", features = ["macros"] }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
base64ct = { version = "1.6.0", features = ["std"] }
chrono = { version = "0.4.38", features = ["serde"] }
core-utils = { path = "crates/core-utils" }
derive_builder = "0.20.0"
dif-exch = { path = "crates/dif-exch" }
ecdsa = "0.16.9"
futures = "0.3.30"
insta = { version = "1.39.0", features = ["redactions", "yaml"] }
k256 = "0.13.3"
openid = { path = "crates/openid" }
proof = { path = "crates/proof" }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = { version = "1.0.120", features = ["alloc"] }
serde_qs = "0.13.0"
test-utils = { path = "crates/test-utils" }
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.5.2", features = ["cors", "set-header", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
uuid = { version = "1.10.0", features = ["fast-rng", "v4"] }
vercre-holder = { path = "vercre-holder" }
vercre-issuer = { path = "vercre-issuer" }
vercre-verifier = { path = "vercre-verifier" }
w3c-vc = { path = "crates/w3c-vc" }

[workspace.metadata.bin]
cargo-xcode = { version = "=1.7.0" }

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
