[workspace]
members = ["test-utils", "vercre-core", "vercre-vci", "vercre-vp", "vercre-wallet"]
resolver = "2"

[workspace.package]
authors = ["Vercre"]
categories = ["decentralized identity", "openid for verifiable data", "privacy", "security", "verifiable credentials"]
# documentation = <use docs.rs>
edition = "2021"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://vercre.io"
keywords = ["credentials", "decentralized", "identity", "openid", "verifiable"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/vercre/vercre"
rust-version = "1.76"
version = "0.1.0-alpha.4"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[workspace.dependencies]
anyhow = "1.0.80"
base64ct = { version = "1.6.0", features = ["std"] }
chrono = { version = "0.4.35", features = ["serde"] }
derive_builder = "0.20.0"
ecdsa = "0.16.9"
k256 = "0.13.3"
lazy_static = "1.4.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tracing = "0.1.40"
uuid = { version = "1.7.0", features = ["fast-rng", "v4"] }
vercre-core = { path = "vercre-core", version = "0.1.0-alpha.3" }

[workspace.metadata.bin]
cargo-xcode = { version = "=1.7.0" }

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true

[profile.release.package.vercre-wallet]
# optimizer kills assembly code
opt-level = 1
