# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html

[graph]
targets = [
  "aarch64-apple-darwin",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
  "wasm32-wasip2",
]
all-features = true
# exclude = []
# no-default-features = false
# features = []

[output]
feature-depth = 1

[advisories]
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    #"Apache-2.0 WITH LLVM-exception",
    "MIT",
    "MIT-0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "OpenSSL",
    "Unicode-3.0"
]

[licenses.private]
ignore = true

# [[licenses.exceptions]] 
# allow = ["OpenSSL"]
# crate = "ring"

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
deny = [{ name = "tokio", deny-multiple-versions = true }]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

