[formatting]
allowed_blank_lines = 1
# array_auto_collapse = true
array_auto_expand = false
column_width = 100
# reorder_arrays = true
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml", "Cargo.toml"]
keys = ["*.dependencies", "build-dependencies", "dependencies", "dev-dependencies", "workspace.dependencies"]

[rule.formatting]
reorder_keys = true
reorder_arrays = true
