[workspace]
members = ["types"]
resolver = "1"

[workspace.package]
edition = "2021"
rust-version = "1.72"
version = "0.1.0"

[workspace.dependencies]
vercre-wallet = { path = "../../../vercre-wallet", features = ["typegen"] }

[workspace.metadata.bin]
cargo-xcode = { version = "=1.7.0" }
