[package]
name = "issuer"
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
axum-extra.workspace = true
axum.workspace = true
chrono.workspace = true
oauth2 = { version = "4.4.2" }
serde.workspace = true
serde_json.workspace = true
serde_qs.workspace = true
test-utils.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
vercre-issuer.workspace = true
