[package]
name = "issuer"
publish = false
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
axum-extra.workspace = true
axum.workspace = true
chrono.workspace = true
oauth2 = { version = "4.4.2" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
credibil-vc = { workspace = true, features = ["issuer"] }
