[package]
edition.workspace = true
name = "mobile-types"
rust-version.workspace = true
version.workspace = true

[dependencies]

[build-dependencies]
vercre-wallet = { workspace = true, features = ["typegen"] }
