[package]
authors.workspace = true
edition.workspace = true
name = "desktop-types"
rust-version.workspace = true
version.workspace = true

[features]
typegen = []

[dependencies]

[build-dependencies]
vercre-wallet = { workspace = true, features = ["typegen"] }
