[build]
# target = "wasm32-unknown-unknown"

[target.x86_64-apple-darwin]
# rustc-env = {DYLD_FALLBACK_LIBRARY_PATH = "$(xcode-select --print-path)/usr/lib/:$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/"}
# rustc-cfg = ['DYLD_FALLBACK_LIBRARY_PATH="/Applications/Xcode.app/Contents/Developer/usr/lib/:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/"']

[alias]
uniffi-bindgen = "run --bin uniffi-bindgen generate"
