[package]
edition.workspace = true
name = "web-types"
rust-version.workspace = true
version.workspace = true

[dependencies]

[build-dependencies]
vercre-wallet = { path = "../../../../vercre-wallet", features = ["typegen"] }
