[package]
edition.workspace = true
name = "wallet"
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
name = "tauri_lib"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
argon2 = { version = "2.1.0", package = "rust-argon2" }
base64ct.workspace = true
iota_stronghold = { git = "https://github.com/vercre/stronghold.rs", package = "iota_stronghold" }
lazy_static = "1.4.0"
log = "^0.4.21"
reqwest = { version = "0.12.4", features = ["json"] }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2.0.0-beta.19", features = ["test"] }
# tauri-plugin-deep-link = "2.0.0-beta.5"
tauri-plugin-http = "2.0.0-beta.7"
# tauri-plugin-log = "2.0.0-beta.4"
# tauri-plugin-shell = "2.0.0-beta.5"
tauri-plugin-store = "2.0.0-beta.6"
thiserror = "1.0.61"

[dev-dependencies]
assert_let_bind = "0.1.1"
tokio = { version = "1.37.0", default-features = false, features = ["fs", "macros", "rt"] }

[build-dependencies]
tauri-build = { version = "2.0.0-beta.15", features = [] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
