[package]
authors.workspace = true
edition.workspace = true
name = "wasm"
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.80"
base64ct = "1.6.0"
chrono = "0.4.34"
ecdsa = "0.16.9"
futures-util = "0.3.30"
gloo-console = "0.3.0"
gloo-net = { version = "0.5.0", features = ["http"] }
k256 = "0.13.3"
serde = "1.0.197"
serde_json = "1.0.114"
sha2 = "0.10.8"
vercre-core = { path = "../../../vercre-core", features = ["wasm"] }
vercre-wallet = { path = "../../../vercre-wallet", features = ["wasm"] }
test-utils = { path = "../../../test-utils" }
yew = { version = "0.21.0", features = ["csr"] }
