[package]
authors.workspace = true
edition.workspace = true
name = "wasm"
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.80"
# futures = "0.3.30"
futures-util = "0.3.30"
gloo-console = "0.3.0"
gloo-net = { version = "0.5.0", features = ["http"] }
# js-sys = "0.3.67"
vercre-wallet = { path = "../../../vercre-wallet", features = ["wasm"] }
# wasm-bindgen = "0.2.90"
# wasm-bindgen-futures = "0.4.40"
# wasm-streams = "0.4.0"
yew = { version = "0.21.0", features = ["csr"] }
