[package]
name = "verifier-provider"
description = "Test utilities"
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
chrono.workspace = true
test-utils.workspace = true
vercre-verifier.workspace = true
