[package]
name = "issuer-provider"
description = "Test utilities"
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
chrono.workspace = true
test-utils.workspace = true
vercre-issuer.workspace = true
