[package]
description = "OpenID compliant Verifiable Credential holder API"
license = "MIT OR Apache-2.0"
name = "vercre-holder"
readme = "README.md"

authors.workspace = true
categories.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
bench = false
crate-type = ["cdylib", "lib", "staticlib"]

[features]
typegen = ["crux_core/typegen", "vercre-core/typegen"]
wasm = ["vercre-core/wasm", "dep:web-sys"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
base64ct = { version = "1.6.0", default-features = false, features = ["std"] }
chrono = { version = "0.4.38", features = ["serde"] }
crux_core = "0.8.0"
crux_http = "0.9.2"
ed25519-dalek = "2.1.1"
lazy_static = "1.4.0"
log = "0.4.21"
olpc-cjson = "0.1.3"
providers.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_qs = "0.13.0"
serde_urlencoded = "0.7.1"
thiserror = "1.0.61"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
tracing.workspace = true
uniffi = { version = "0.27.3", features = ["cli"] }
urlencoding = "2.1.3"
uuid.workspace = true
vercre-core.workspace = true
vercre-issuer.workspace = true
vercre-verifier.workspace = true
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = ["console"], optional = true }
async-trait = "0.1.80"
vercre-vc.workspace = true

[dev-dependencies]
assert_let_bind = "0.1.1"
axum = { version = "0.7.5", features = ["macros"] }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
axum-test = "15.0.1"
insta = { version = "1.39.0", features = ["redactions", "yaml"] }
test-utils.workspace = true
tokio = { version = "1.38.0", default-features = false, features = ["fs", "macros", "rt"] }
tower-http = { version = "0.5.2", features = ["trace"] }

[build-dependencies]
uniffi = { version = "0.27.3", features = ["build"] }

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.27.3", features = ["cli"] }
