[package]
name = "verifier"
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
axum-extra.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
test-utils.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
vercre-verifier.workspace = true
