[package]
name = "holder-provider"
description = "Test utilities"
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
base64ct.workspace = true
chrono.workspace = true
dif-exch.workspace = true
ecdsa.workspace = true
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
issuer-provider = { path = "../issuer" }
serde_json.workspace = true
vercre-holder.workspace = true
vercre-issuer.workspace = true
vercre-verifier.workspace = true
verifier-provider = { path = "../verifier" }
