# extend = "../../Makefile.toml"

[tasks.gen]
dependencies = ["gen-app", "gen-web"]
# cargo uniffi-bindgen -l swift -l kotlin -o ./gen ./src/shared.udl

[tasks.gen-app]
command = "cargo"
args = ["build", "--manifest-path", "./examples/app/Cargo.toml"]

[tasks.gen-web]
command = "cargo"
args = ["build", "--manifest-path", "./examples/web/Cargo.toml"]

[tasks.build-wasm]
command = "wasm-pack"
args = ["build", "--scope", "vercre", "--out-dir", "./pkg"]

[tasks.publish-wasm]
dependencies = ["build-wasm"]
command = "npm"
args = ["publish", "./pkg", "--access", "public"]

[tasks.publish-types]
dependencies = ["gen-web"]
script = [
    "cd ./examples/web/types/gen/typescript/",
    "npm pkg set name=\"@vercre/shared_types\"",
    "npm pkg set version=\"0.1.0-alpha.4\"",
    "npm publish --access public"
]
